apiVersion: index.opensearch.crossplane.io/v1alpha1
kind: Template
metadata:
  annotations:
    meta.upbound.io/example-id: opensearch/v1alpha1/indextemplate
  labels:
    testing.upbound.io/example-name: writer
  name: writer
spec:
  forProvider:
    name: indextemplate
    body: |
      {
        "template": "te*",
        "settings": {
          "number_of_shards": 1
        },
        "mappings": {
          "type1": {
            "_source": {
              "enabled": false
            },
            "properties": {
              "host_name": {
                "type": "keyword"
              },
              "created_at": {
                "type": "date",
                "format": "EEE MMM dd HH:mm:ss Z YYYY"
              }
            }
          }
        }
      }
